--DIM_CHANNEL VIEW
CREATE OR REPLACE SECURE VIEW PUBLIC.VIEW_DIM_CHANNEL
AS
SELECT DIMCHANNELID,
SOURCECHANNELID,
SOURCECHANNELCATEGORYID,
CHANNEL,
CHANNELCATEGORY
FROM DIM_CHANNEL

--DIM_CUSTOMER VIEW
CREATE OR REPLACE SECURE VIEW PUBLIC.VIEW_DIM_CUSTOMER
AS
SELECT DIMCUSTOMERID,
DIMLOCATIONID,
SOURCECUSTOMERID,
FULLNAME,
FIRSTNAME,
LASTNAME,
GENDER,
EMAILADDRESS,
PHONENUMBER
FROM DIM_CUSTOMER

--DIM_DATE VIEW
CREATE OR REPLACE SECURE VIEW PUBLIC.VIEW_DIM_DATE
AS
SELECT FISCAL_HALFYEAR,
WEEK_NUM_IN_YEAR,
MONTH_NAME,
DAY_ABBREV,
WEEK_END_DATE,
MONTH_END_IND,
DAY_NUM_IN_MONTH,
DAY_NUM_IN_YEAR,
WEEK_BEGIN_DATE_NKEY,
MONTH_ABBREV,
CURRENT_ROW_IND,
DAY_NAME,
FISCAL_MONTH_NUM,
US_HOLIDAY_IND,
FISCAL_YEAR,
WEEK_END_DATE_NKEY,
QUARTER,
FULL_DATE_DESC,
FISCAL_WEEK_NUM,
DATE,
MONTH_NUM_IN_YEAR,
FISCAL_YEARMONTH,
EXPIRATION_DATE,
WEEKDAY_IND,
FISCAL_YEARQUARTER,
DATE_PKEY,
YEAR,
FISCAL_QUARTER,
YEARMONTH,
WEEK_BEGIN_DATE,
SQL_TIMESTAMP,
EFFECTIVE_DATE,
YEARQUARTER,
DAY_NUM_IN_WEEK,
_HOLIDAY_IND
FROM DIM_DATE

--DIM_LOCATION VIEW
CREATE OR REPLACE SECURE VIEW PUBLIC.VIEW_DIM_LOCATION
AS
SELECT DIMLOCATIONID,
SOURCELOCATIONID,
POSTALCODE,
ADDRESS,
CITY,
STATEPROVINCE,
COUNTRY
FROM DIM_LOCATION

--DIM_PRODUCT VIEW
CREATE OR REPLACE SECURE VIEW PUBLIC.VIEW_DIM_PRODUCT
AS
SELECT PRODUCTWHOLESALEPRICE,
SOURCEPRODUCTTYPEID,
PRODUCTCOST,
SOURCEPRODUCTCATEGORYID,
PRODUCTPROFITMARGINUNITPERCENT,
SOURCEPRODUCTID,
PRODUCTWHOLESALEUNITPROFIT,
PRODUCTNAME,
PRODUCTRETAILPRICE,
PRODUCTTYPE,
PRODUCTCATEGORY,
PRODUCTRETAILPROFIT,
DIMPRODUCTID
FROM DIM_PRODUCT

--DIM_RESELLER VIEW
CREATE OR REPLACE SECURE VIEW PUBLIC.VIEW_DIM_RESELLER
AS
SELECT DIMLOCATIONID,
SOURCERESELLERID,
CONTACTNAME,
DIMRESELLERID,
PHONENUMBER,
EMAILADDRESS
FROM DIM_RESELLER

--DIM_STORE VIEW
CREATE OR REPLACE SECURE VIEW PUBLIC.VIEW_DIM_STORE
AS
SELECT STORENUMBER,
SOURCESTOREID,
DIMSTOREID,
DIMLOCATIONID,
STOREMANAGER
FROM DIM_STORE

--FACT_PRODUCTSALESTARGET VIEW
CREATE OR REPLACE SECURE VIEW PUBLIC.VIEW_FACT_PRODUCTSALETARGET
AS
SELECT DIMTARGETDATEID,
PRODUCTTARGETSALESQUANTITY,
DIMPRODUCTID
FROM FACT_PRODUCTSALETARGET

--FACT_SALESACTUAL VIEW
CREATE OR REPLACE SECURE VIEW PUBLIC.VIEW_FACT_SALESACTUAL
AS
SELECT DIMPRODUCTID,
SALEAMOUNT,
SOURCESALESHEADERID,
DIMRESELLERID,
DIMCUSTOMERID,
DIMSTOREID,
SALEUNITPRICE,
SOURCESALESDETAILID,
DIMSALESDATEID,
SALETOTALPROFIT,
SALEEXTENDEDCOST,
DIMLOCATIONID,
DIMCHANNELID,
SALEQUANTITY
FROM FACT_SALESACTUAL

--FACT_SRCSALESTARGET VIEW
CREATE OR REPLACE SECURE VIEW PUBLIC.VIEW_FACT_SRCSALESTARGET
AS
SELECT DIMSTOREID,
SALESTARGETAMOUNT,
DIMRESELLERID,
DIMCHANNELID,
DIMTARGETDATEID
FROM FACT_SRCSALESTARGET